// <auto-generated />
using Candyshop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Candyshop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200605211340_SeedDb")]
    partial class SeedDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Candyshop.Models.Candy", b =>
                {
                    b.Property<int>("CandyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CandyId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Candies");

                    b.HasData(
                        new
                        {
                            CandyId = 1,
                            CategoryId = 1,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\thumbnail\\chocolet-Thumbnail.jpg",
                            ImageUrl = "~\\Images\\chocolet.candy.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Assorted Chocolet Candy",
                            Price = 4.95m
                        },
                        new
                        {
                            CandyId = 2,
                            CategoryId = 1,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\thumbnail\\chocolateCandy-small.jpg",
                            ImageUrl = "~\\Images\\chocolateCandy.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Chocolet Candy",
                            Price = 3.95m
                        },
                        new
                        {
                            CandyId = 3,
                            CategoryId = 1,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\thumbnail\\chocolateCandy2-small.jpg",
                            ImageUrl = "~\\Images\\chocolateCandy2.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Chocolet Candy",
                            Price = 295m
                        },
                        new
                        {
                            CandyId = 4,
                            CategoryId = 1,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\thumbnail\\chocolateCandy3-small.jpg",
                            ImageUrl = "~\\Images\\chocolateCandy3.jpg",
                            IsInStock = false,
                            IsOnSale = true,
                            Name = "Assorted Chocolet Candy",
                            Price = 6.95m
                        },
                        new
                        {
                            CandyId = 5,
                            CategoryId = 2,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\thumbnail\\FruitCandy-small.jpg",
                            ImageUrl = "~\\Images\\FruitCandy.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Fruit Candy",
                            Price = 6.95m
                        },
                        new
                        {
                            CandyId = 6,
                            CategoryId = 2,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\thumbnail\\fruitCandy2-small.jpg",
                            ImageUrl = "~\\Images\\fruitCandy2.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Assorted Fruit Candy",
                            Price = 3.95m
                        },
                        new
                        {
                            CandyId = 7,
                            CategoryId = 2,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\fruitCandy3-small.jpg",
                            ImageUrl = "~\\Images\\fruitCandy3.jpg",
                            IsInStock = false,
                            IsOnSale = true,
                            Name = "Assorted Fruit Candy",
                            Price = 4.95m
                        },
                        new
                        {
                            CandyId = 8,
                            CategoryId = 3,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\gummyCandy-small.jpg",
                            ImageUrl = "~\\Images\\gummyCandy.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Assorted Gummy Candy",
                            Price = 4.95m
                        },
                        new
                        {
                            CandyId = 9,
                            CategoryId = 3,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\gummyCandy2-small.jpg",
                            ImageUrl = "~\\Images\\gummyCandy2.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Gummy Candy",
                            Price = 6.95m
                        },
                        new
                        {
                            CandyId = 10,
                            CategoryId = 3,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\gummyCandy3-small.jpg",
                            ImageUrl = "~\\Images\\gummyCandy3.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Gummy Candy",
                            Price = 4.95m
                        },
                        new
                        {
                            CandyId = 11,
                            CategoryId = 4,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\halloweenCandy-small.jpg",
                            ImageUrl = "~\\Images\\halloweenCandy.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Halloween Candy",
                            Price = 3.95m
                        },
                        new
                        {
                            CandyId = 12,
                            CategoryId = 4,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\halloweenCandy2-small.jpg",
                            ImageUrl = "~\\Images\\halloweenCandy2.jpg",
                            IsInStock = false,
                            IsOnSale = true,
                            Name = "Assorted Halloween Candy",
                            Price = 5.95m
                        },
                        new
                        {
                            CandyId = 13,
                            CategoryId = 4,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\halloweenCandy3-small.jpg",
                            ImageUrl = "~\\Images\\halloweenCandy3.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Halloween Candy",
                            Price = 6.95m
                        },
                        new
                        {
                            CandyId = 14,
                            CategoryId = 5,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\hardCandy-small.jpg",
                            ImageUrl = "~\\Images\\hardCandy.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Assorted Hard Candy",
                            Price = 3.95m
                        },
                        new
                        {
                            CandyId = 15,
                            CategoryId = 5,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\hardCandy2-small.jpg",
                            ImageUrl = "~\\Images\\hardCandy2.jpg",
                            IsInStock = false,
                            IsOnSale = true,
                            Name = "Assorted Hard Candy",
                            Price = 2.95m
                        },
                        new
                        {
                            CandyId = 16,
                            CategoryId = 5,
                            Description = " Lorem ipsum dolor sit amet, consectetur adiposcing elit, sed do eiusmod tempor...",
                            ImageThumbnailUrl = "~\\Images\\hardCandy3-small.jpg",
                            ImageUrl = "~\\Images\\hardCandy3.jpg",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Assorted Hard Candy",
                            Price = 5.95m
                        });
                });

            modelBuilder.Entity("Candyshop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescriptin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categores");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Chocolate Candy"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Fruit Candy"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Gummy Candy"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Halloween Candy"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Hard Candy"
                        });
                });

            modelBuilder.Entity("Candyshop.Models.Candy", b =>
                {
                    b.HasOne("Candyshop.Models.Category", "Category")
                        .WithMany("Candies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
